# Register
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "email": "omrigo3145@gmail.com",
    "password": "om3fds12"
}
###

# Login
POST http://localhost:3001/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "omrigo312@gmail.com",
    "password": "omrigo312"
}
###

# Get all vacations
GET http://localhost:3001/api/vacations HTTP/1.1
###

# Create a vacation
POST http://localhost:3001/api/vacations HTTP/1.1
content-type: application/json

{
    "description": "Come stay at out wonderful beach resort",
    "destination":"Vietnam",
    "imageUrl": "http://www.prettyimage.com",
    "price": "5000",
    "startDate": "2021-01-06",
    "endDate": "2021-01-06"
}