# Register
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "email": "omrigo3145@gmail.com",
    "password": "om3fds12"
}
###

# Login
POST http://localhost:3001/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "omrigo312@gmail.com",
    "password": "omrigo312"
}
###

# Get all vacations
GET http://localhost:3001/api/vacations HTTP/1.1
###

# Create a vacation
POST http://localhost:3001/api/vacations HTTP/1.1
content-type: application/json

{
    "description": "Come to the wild safaris of Africa and enjoy a sight into the true nature.",
    "destination":"Kenya & Tanzania",
    "imageUrl": "https://safarisafricana.com/wp-content/uploads/2020/05/Copy-of-SAFAF-2X1-images-60.jpg",
    "price": "699",
    "startDate": "2021-07-04",
    "endDate": "2021-08-13"
}
###

# Delete a vacation
DELETE http://localhost:3001/api/vacations/2 HTTP/1.1
###